name: AFIDS Validator Continuous Integration

on:
    pull_request:
        types: [opened]

jobs:
    build:
        name: Setup environment
        runs-on: ubuntu-latest

        steps:
            - name: Checkout pull request branch
              uses: actions/checkout@master
              with:
                  ref: ${{ github.sha }}

            - name: Select python version
              uses: actions/setup-python@v1
              with:
                  python-version: '3.x'

            - name: Setup python environment
              shell: bash
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt --no-cache-dir


    test:
        name: Test afids-validator
        needs: [build]
        runs-on: ubuntu-latest

        steps:
            - name: Run unit test
              shell: bash
              run: |
                python -m unittest


    review:
        name: Assign reviewer if CI passes
        needs: [build, test]
        runs-on: ubuntu-latest

        steps:
            - name: Assign a reviewer
              uses: kentaro-m/auto-assign-action@v1.0.1
              with:
                  repo-token: "${{ secrets.GITHUB_TOKEN }}"
