name: AFIDs Validator App Deployment

on:
  merge:
    branches:
      - master

jobs:
  build:
    name: Set up environment & deploy to heroku
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
      - uses: actions/checkout@master

      - name: Deploy heroku app
      - uses: akhileshns/heroku-deploy@v3.0.4
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}} # Heroku API Key 
          heroku_app_name: fidvalidator # Heroku app name
          heroku_email: ${{secrets.HEROKU_EMAIL}} # Heroku email