name: AFIDs Validator PR Review

on:
    pull_request:
        types: [opened, reopened, ready_for_review]
    issues:
        types: [poened]

jobs:
    review:
        name: Assign reviewer
        runs-on: ubuntu-latest

        steps:
            - name: Assign a reviewer
              uses: kentaro-m/auto-assign-action@v1.0.1
              with:
                  repo-token: "${{ secrets.GITHUB_TOKEN }}"
